import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion} from 'framer-motion';
import {Menu,X,Search,ArrowRight,CalendarDays,Calculator,Phone,MapPin,ChevronDown} from 'lucide-react';
import './styles.css';

const cars=[
 {id:1,make:'Mercedes-Benz',model:'AMG GT 63',year:2025,type:'Performance',price:185000000,img:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',spec:'4.0L V8 • 585 hp • Automatic'},
 {id:2,make:'Toyota',model:'Land Cruiser 300',year:2025,type:'SUV',price:145000000,img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80',spec:'3.5L V6 • 409 hp • 4WD'},
 {id:3,make:'Range Rover',model:'Sport HSE',year:2024,type:'SUV',price:175000000,img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80',spec:'3.0L I6 • 355 hp • AWD'},
 {id:4,make:'BMW',model:'M4 Competition',year:2025,type:'Performance',price:118000000,img:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',spec:'3.0L I6 • 503 hp • Automatic'},
 {id:5,make:'Lexus',model:'LX 600',year:2024,type:'Luxury SUV',price:155000000,img:'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80',spec:'3.4L V6 • 409 hp • 4WD'},
 {id:6,make:'Porsche',model:'911 Carrera',year:2025,type:'Sports',price:210000000,img:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=80',spec:'3.0L Flat-6 • 379 hp • PDK'}
];
const money=n=>'₦'+n.toLocaleString('en-NG');
function App(){
 const [open,setOpen]=useState(false),[filter,setFilter]=useState('All'),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[modal,setModal]=useState(null);
 const filtered=cars.filter(c=>(filter==='All'||c.type===filter)&&(`${c.make} ${c.model}`.toLowerCase().includes(search.toLowerCase())));
 return <div>
  <div className="demo">DEMO SHOWCASE • FICTIONAL DEALERSHIP CONTENT</div>
  <nav><div className="logo">CREST<span>MOTORS</span></div><div className={'links '+(open?'show':'')}><a href="#inventory">Inventory</a><a href="#services">Services</a><a href="#finance">Finance</a><a href="#about">About</a><button onClick={()=>setModal('test')}>Book a Test Drive</button></div><button className="menub" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>
  <section className="hero"><div className="heroCopy"><p className="eyebrow">PREMIUM AUTOMOTIVE SHOWROOM</p><h1>Find the car<br/><em>worth driving.</em></h1><p>Discover premium vehicles, transparent pricing and a smoother way to move from browsing to the driver's seat.</p><button onClick={()=>document.getElementById('inventory').scrollIntoView({behavior:'smooth'})}>Explore Inventory <ArrowRight size={18}/></button></div><div className="heroCar"></div></section>
  <section className="finder"><div><small>QUICK VEHICLE FINDER</small><h2>What are you looking for?</h2></div><div className="controls"><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>SUV</option><option>Performance</option><option>Luxury SUV</option><option>Sports</option></select><div className="search"><Search size={18}/><input placeholder="Search make or model" value={search} onChange={e=>setSearch(e.target.value)}/></div><button onClick={()=>document.getElementById('inventory').scrollIntoView({behavior:'smooth'})}>Find Cars</button></div></section>
  <section id="inventory" className="section"><div className="sectionHead"><div><p className="eyebrow">OUR COLLECTION</p><h2>Featured inventory</h2></div><p>Hand-picked vehicles selected for performance, comfort and presence.</p></div><div className="grid">{filtered.map(c=><motion.article whileHover={{y:-8}} className="car" key={c.id}><div className="carImg"><img src={c.img}/><span>{c.year}</span></div><div className="carBody"><small>{c.make}</small><h3>{c.model}</h3><p>{c.spec}</p><strong>{money(c.price)}</strong><button onClick={()=>setSelected(c)}>View Vehicle <ArrowRight size={16}/></button></div></motion.article>)}</div></section>
  <section id="services" className="dark section"><p className="eyebrow">BEYOND THE SHOWROOM</p><h2>Everything you need<br/>to make the move.</h2><div className="serviceGrid"><div><CalendarDays/><h3>Test Drives</h3><p>Choose a vehicle and request a preferred date. We'll handle the rest.</p><button onClick={()=>setModal('test')}>Schedule <ArrowRight/></button></div><div><Calculator/><h3>Finance</h3><p>Explore estimated monthly payments before you visit the showroom.</p><button onClick={()=>setModal('finance')}>Calculate <ArrowRight/></button></div><div><ArrowRight/><h3>Trade-In</h3><p>Tell us about your current vehicle and start your valuation enquiry.</p><button onClick={()=>setModal('trade')}>Value My Car <ArrowRight/></button></div></div></section>
  <section id="finance" className="finance section"><div><p className="eyebrow">DRIVE WITH CLARITY</p><h2>Know your numbers<br/>before you buy.</h2><p>Use our simple finance estimate to explore what a vehicle could look like within your monthly budget.</p></div><div className="calc"><label>Vehicle price<input defaultValue="75000000"/></label><label>Deposit<input defaultValue="15000000"/></label><label>Term<select defaultValue="48"><option value="36">36 months</option><option value="48">48 months</option><option value="60">60 months</option></select></label><div className="estimate"><small>ESTIMATED MONTHLY</small><b>₦2,150,000</b><span>Demo estimate only — not a finance offer.</span></div></div></section>
  <section id="about" className="about section"><div><p className="eyebrow">THE CREST STANDARD</p><h2>A modern showroom<br/>built around trust.</h2></div><div><p>Crest Motors is a fictional premium dealership created as a demonstration project. The experience is designed around the things real buyers care about: quality stock, clear information, simple enquiries and an easy route to the showroom.</p><div className="stats"><b>250+<small>Vehicles sourced</small></b><b>12<small>Premium brands</small></b><b>24/7<small>Online enquiries</small></b></div></div></section>
  <footer><div className="logo">CREST<span>MOTORS</span></div><div><p><MapPin size={15}/> Lagos, Nigeria</p><p><Phone size={15}/> +234 800 CREST</p></div><p>© 2026 Crest Motors Demo</p></footer>
  {selected&&<div className="overlay" onClick={()=>setSelected(null)}><div className="vehicleModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X/></button><img src={selected.img}/><div><small>{selected.make} • {selected.year}</small><h2>{selected.model}</h2><p>{selected.spec}</p><h3>{money(selected.price)}</h3><button onClick={()=>{setSelected(null);setModal('test')}}>Book a Test Drive <ArrowRight/></button></div></div></div>}
  {modal&&<div className="overlay"><div className="formModal"><button className="close" onClick={()=>setModal(null)}><X/></button><p className="eyebrow">CREST MOTORS</p><h2>{modal==='finance'?'Finance Enquiry':modal==='trade'?'Trade-In Enquiry':'Book a Test Drive'}</h2><input placeholder="Full name"/><input placeholder="Phone number"/><input placeholder="Email address"/>{modal==='test'&&<select><option>Select preferred vehicle</option>{cars.map(c=><option key={c.id}>{c.make} {c.model}</option>)}</select>}<textarea placeholder="Tell us how we can help"/><button onClick={()=>setModal(null)}>Send Enquiry <ArrowRight/></button></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
